kind: Service
apiVersion: v1
metadata:
  name: autoscaler-expander
  namespace: autoscaler-expander
  labels:
    app: autoscaler-expander
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: autoscaler-expander-certs
spec:
  selector:
    app: autoscaler-expander
  type: ClusterIP
  ports:
    - name: grpc
      port: 7000
      targetPort: 7000
      protocol: TCP
      appProtocol: grpc


